[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = 'source /home/kakehi/.config/nvim/plugins/coc.rc.vim'

#[[plugins]]
#repo = 'neoclide/coc-neco'

#[[plugins]]
#repo = 'Shougo/neco-vim'

[[plugins]]
 repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
"let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
let g:airline_theme = 'onedark'
'''

[[plugin]]
repo = 'majutsushi/tagbar'

[[plugin]]
repo = 'tpope/vim-fugitive'
# fugitive 逃亡者



